theme: jekyll-theme-tactile

title: Analyzing Financial Success in the College Football Playoff
description: Financial analysis of the four teams selected in the College Football Playoff from 2014 - 2017.

author:
  name: Will Pope

social-network-links:
  linkedin: willcpope
