theme: jekyll-theme-time-machine

title: Analyzing College Football Team ROI
description: An analysis of the final CFP Top 25 from 2014 - 2017.

author:
  name: Will Pope

social-network-links:
  linkedin: willcpope
